---

- hosts: homeassistant
  vars:
    - homeassistant_git_config: "https://github.com/rmalleman/home-assistant-config"
    - homeassistant_environment_file: "/home/{{ homeassistant_user }}/ha.env"
  roles:
    - role: ansible-homeassistant
  tasks:
    - name: copy env file
      copy:
        src: files/ha.env
        dest: /home/{{ homeassistant_user }}/ha.env
      become: true
      become_user: "{{ homeassistant_user }}"
